using System.Text.Json.Serialization;

namespace Snail.Toolkit.AI.Contracts.Schema;

/// <summary>
/// Represents a single message within a conversation exchange.
/// </summary>
/// <param name="Role">The role of the message author (e.g., "system", "user", "assistant", or "tool").</param>
/// <param name="Content">The textual content of the message.</param>
/// <param name="Thinking">The internal reasoning or "chain of thought" generated by the model, if applicable.</param>
/// <param name="Images">An optional collection of Base64 encoded images or image URLs associated with the message.</param>
/// <param name="ToolCalls">A list of tool calls generated by the model that require execution.</param>
internal record Message(
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("content")] string Content,
    [property: JsonPropertyName("thinking")] string? Thinking,
    [property: JsonPropertyName("images")] IEnumerable<string>? Images,
    [property: JsonPropertyName("tool_calls")] IEnumerable<ToolCall>? ToolCalls
);