using System.Text.Json.Serialization;
using Snail.Toolkit.AI.Contracts.Schema;

namespace Snail.Toolkit.AI.Contracts.Responses;

/// <summary>
/// Represents a structured response from a chat-based model interaction.
/// </summary>
internal record ChatResponse : ResponseBase
{
    /// <summary>
    /// Gets the message generated by the model, containing the role, content, 
    /// and any optional tool calls or reasoning.
    /// </summary>
    [JsonPropertyName("message")] 
    public required Message Message { get; init; }
}