using System.Text.Json.Serialization;

namespace Snail.Toolkit.AI.Contracts.Responses;

/// <summary>
/// Represents a non-chat completion response from the model.
/// </summary>
internal record GenerateResponse : ResponseBase
{
    /// <summary>
    /// Gets the main text generated by the model in response to the prompt.
    /// </summary>
    [JsonPropertyName("response")]
    public string Response { get; init; } = string.Empty;

    /// <summary>
    /// Gets the internal reasoning or "chain of thought" produced by the model 
    /// before providing the final response.
    /// </summary>
    [JsonPropertyName("thinking")]
    public string? Thinking { get; init; }
}